# src/latest_ai_development/config/tasks.yaml
research_task:
  description: >
    Research and identify events and activities in {topic}.
    If specific dates are unavailable, find seasonal activities appropriate for the time period.
    Consider weather conditions, operating hours, and availability.
    Include pricing, location details, and any special requirements.
  expected_output: >
    A list of 10 recommended events/activities, each including:
    - Date and time availability
    - Location and transportation options
    - Pricing and booking requirements
    - Weather considerations
    - Estimated duration
  agent: researcher

reporting_task:
  description: >
    Organize the selected events and activities into sensible categories, creating a type of "menu" for the user.
  expected_output: >
    A table of events and activities, with columns for:
    - Date and time
    - Activity name
    - Location or Address
    - Duration
    - Cost
    - Notes/Recommendations
  agent: reporting_analyst
  output_file: itinerary.md
